In [ ]:
from google.colab import drive
import os


drive.mount('/content/drive',force_remount=True)

os.chdir('/content/drive/MyDrive/ML')
os.listdir()

Mounted at /content/drive

['auto-mpg_sample.xml',
 'scaling_comparison.png',
 'correlation_matrix.png',
 'pca_scree_plot.png',
 'pca_components_analysis.png',
 'pca_projection.png',
 'auto-mpg.gsheet',
 'cleaned.csv',
 'indic-decibel-aqa-v0.1',
 '1_ML.ipynb',
 'auto-mpg.csv',
 'auto-mpg1.csv',
 'iris.ipynb',
 'indic-decibel-aqa-v0.1.ipynb',
 'wine.csv']

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML/auto-mpg.csv')
df.head()

,Unnamed: 0,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,0,18.0,8,307.0,130.0,3504,12.0,70,1
1,1,15.0,8,350.0,165.0,3693,11.5,70,1
2,2,18.0,8,318.0,150.0,3436,11.0,70,1
3,3,16.0,8,304.0,150.0,3433,12.0,70,1
4,4,17.0,8,302.0,140.0,3449,10.5,70,1

In [ ]:
df.replace('?',np.nan,inplace=True)
df['horsepower'] = pd.to_numeric(df['horsepower'])
df.dropna()

,Unnamed: 0,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,0,18.0,8,307.0,130.0,3504,12.0,70,1
1,1,15.0,8,350.0,165.0,3693,11.5,70,1
2,2,18.0,8,318.0,150.0,3436,11.0,70,1
3,3,16.0,8,304.0,150.0,3433,12.0,70,1
4,4,17.0,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...,...,...
393,393,27.0,4,140.0,86.0,2790,15.6,82,1
394,394,44.0,4,97.0,52.0,2130,24.6,82,2
395,395,32.0,4,135.0,84.0,2295,11.6,82,1
396,396,28.0,4,120.0,79.0,2625,18.6,82,1
397,397,31.0,4,119.0,82.0,2720,19.4,82,1

In [ ]:
if 'car name' in df.columns:
  df = df.drop(columns=['car name'])

In [ ]:
X = df.drop(columns=['mpg'])
y = df['mpg']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
remaining_features = list(X.columns)
selected_features = []
best_score = -np.inf

In [ ]:
while remaining_features:
  scores = []

In [ ]:
for feature in remaining_features:
  features_to_test = selected_features + [feature]

In [ ]:
model = LinearRegression()
model.fit(X_train[features_to_test], y_train)

y_pred = model.predict(X_test[features_to_test])
score = r2_score(y_test, y_pred)

scores.append((score, feature))

In [ ]:
scores.sort(reverse=True)
current_best_score, best_feature = scores[0]

In [ ]:
if current_best_score > best_score:
    best_score = current_best_score
    selected_features.append(best_feature)
    remaining_features.remove(best_feature)

    print(f"Added: {best_feature}, R2 Score: {best_score:.4f}")
else:
    break

print("\nFinal Selected Features:")
print(selected_features)